package com.chenyg.uibinder.j2se;

import javax.swing.*;
import java.awt.*;

/**
 * Created by 宇宙之灵 on 2015/9/12.
 */
class InputDialog
{
    JPanel mainPanel;
    JPanel contentPanel;
    JButton okButton;
    JButton cancelButton;
    JTextArea textArea;
    JTextField textField;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2), null));
        contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(contentPanel, BorderLayout.CENTER);
        contentPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(3, 3, 3, 3), null));
        textArea = new JTextArea();
        contentPanel.add(textArea, BorderLayout.CENTER);
        textField = new JTextField();
        contentPanel.add(textField, BorderLayout.NORTH);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 5));
        mainPanel.add(panel1, BorderLayout.SOUTH);
        cancelButton = new JButton();
        cancelButton.setText("cancel");
        panel1.add(cancelButton);
        okButton = new JButton();
        okButton.setText("ok");
        panel1.add(okButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return mainPanel;
    }
}
